server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application-name: scheduler-bot
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:scheduler_tg_bot}
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:postgres}

logging:
  level:
    root: INFO
    org.springframework.web: INFO